from django.contrib import admin
from .models import *
admin.site.register(access)
admin.site.register(user_profile)
admin.site.register(price)
admin.site.register(client)
admin.site.register(cashbox)
admin.site.register(storage)
admin.site.register(engine)
admin.site.register(car)
admin.site.register(category)
admin.site.register(manufacturer)
admin.site.register(product)
admin.site.register(type_operation_money)
admin.site.register(operation_money)
admin.site.register(type_operation_product)
admin.site.register(operation_product)
admin.site.register(memory_action)
admin.site.register(characteristics)
admin.site.register(characteristics_value)
admin.site.register(amount_on_storage)
admin.site.register(price_value)
admin.site.register(trading_product_in_basket)
admin.site.register(operation_product_product_instance)
admin.site.register(operation_product_cashbox_instance)
admin.site.register(characteristics_choices)
admin.site.register(part_of_car)