# Generated by Django 2.0.4 on 2018-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaximum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='edinica',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
