# Generated by Django 2.0.7 on 2018-08-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaximum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ext_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=128, verbose_name='Трансмисия'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date1',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала выпуска'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date2',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания выпуска'),
        ),
    ]
