# Generated by Django 2.0.4 on 2018-06-24 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automaximum', '0002_characteristics_edinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='part_of_car',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automaximum.engine'),
        ),
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='part_of_car',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automaximum.car'),
        ),
        migrations.AlterField(
            model_name='part_of_car',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automaximum.product'),
        ),
    ]
