# Generated by Django 2.0.7 on 2018-08-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaximum', '0002_auto_20180812_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='info',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
    ]
