# Generated by Django 2.0.7 on 2018-08-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaximum', '0003_engine_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
    ]
