# Generated by Django 2.0.4 on 2018-06-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automaximum', '0005_auto_20180627_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_operation_product',
            name='default_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automaximum.client', verbose_name='Стандартный клиент'),
        ),
        migrations.AlterField(
            model_name='type_operation_product',
            name='creates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automaximum.type_operation_money', verbose_name='Создает кассовую операцию'),
        ),
        migrations.AlterField(
            model_name='type_operation_product',
            name='default_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automaximum.price', verbose_name='Стандартная цена'),
        ),
    ]
