# Generated by Django 2.0.4 on 2018-06-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaximum', '0006_auto_20180627_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_operation_product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
