# Generated by Django 2.0.4 on 2018-07-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaximum', '0007_auto_20180627_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='deletefree',
            field=models.BooleanField(default=True),
        ),
    ]
