# Generated by Django 2.0.4 on 2018-07-11 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automaximum', '0008_auto_20180705_0354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='access_level',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='amount_on_storage',
            options={'ordering': ['storage']},
        ),
        migrations.AlterModelOptions(
            name='cashbox',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='characteristics_choices',
            options={'ordering': ['characteristics']},
        ),
        migrations.AlterModelOptions(
            name='characteristics_value',
            options={'ordering': ['characteristics']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='price_value',
            options={'ordering': ['price']},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='trading_product_in_basket',
            options={'ordering': ['product']},
        ),
        migrations.AlterModelOptions(
            name='type_operation_money',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='type_operation_product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user_profile',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='cashbox',
            name='admin_cashbox',
            field=models.BooleanField(default=False, verbose_name='Касса администратора'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.ManyToManyField(blank=True, to='automaximum.engine', verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='subcategory_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automaximum.car', verbose_name='Подкатегория от'),
        ),
        migrations.AlterField(
            model_name='category',
            name='characteristics_forname',
            field=models.ManyToManyField(blank=True, related_name='characteristics_forname', to='automaximum.characteristics', verbose_name='Характеристики в названии названия'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='edinica',
            field=models.CharField(blank=True, max_length=8, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='type',
            field=models.CharField(choices=[('int', 'Число'), ('choice', 'Выбор'), ('string', 'Текст')], default='int', max_length=22, verbose_name='Вид характеристики'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adress',
            field=models.CharField(blank=True, max_length=128, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='card',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automaximum.price', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='commentary',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='operation_money',
            name='cash',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='operation_money',
            name='cashbox_recieve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbox_recieve', to='automaximum.cashbox', verbose_name='Касса-получатель'),
        ),
        migrations.AlterField(
            model_name='operation_money',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automaximum.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='operation_money',
            name='commentary',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='operation_money',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='operation_product_cashbox_instance',
            name='cash',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='operation_product_product_instance',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automaximum.product'),
        ),
        migrations.AlterField(
            model_name='operation_product_product_instance',
            name='product_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='operation_product_product_instance',
            name='product_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за ед.'),
        ),
        migrations.AlterField(
            model_name='part_of',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='part_of_car',
            name='part_of',
            field=models.ManyToManyField(blank=True, to='automaximum.part_of', verbose_name='Часть автомобиля'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=256, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article_alt',
            field=models.CharField(blank=True, max_length=256, verbose_name='Альтернативный артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='car',
            field=models.ManyToManyField(blank=True, to='automaximum.car', verbose_name='Машины'),
        ),
        migrations.AlterField(
            model_name='product',
            name='commentary',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='commentary',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='type_operation_product',
            name='default_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automaximum.client', verbose_name='Клиент по умолчанию'),
        ),
        migrations.AlterField(
            model_name='type_operation_product',
            name='default_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automaximum.price', verbose_name='Цена по умолчанию'),
        ),
    ]
