# Generated by Django 2.0.4 on 2018-07-13 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automaximum', '0009_auto_20180711_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date1',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата начала выпуска'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date2',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата окончания выпуска'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='commentary',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='useinfullname',
            field=models.BooleanField(default=True, verbose_name='Использовать в названии'),
        ),
        migrations.AlterField(
            model_name='operation_product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='type_operation_money',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='type_operation_money',
            name='type',
            field=models.CharField(choices=[('minus', 'Расход'), ('plus', 'Приход'), ('minusplus', 'Перемещение')], default='minus', max_length=22, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='type_operation_product',
            name='type',
            field=models.CharField(choices=[('minus', 'Расход'), ('plus', 'Приход'), ('minusplus', 'Перемещение')], default='minus', max_length=22, verbose_name='Вид'),
        ),
    ]
