# Generated by Django 2.0.4 on 2018-07-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaximum', '0010_auto_20180713_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='supplier',
            field=models.BooleanField(default=False, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='characteristics_choices',
            name='text',
            field=models.CharField(blank=True, max_length=128, verbose_name='Значение'),
        ),
    ]
