# Generated by Django 2.0.4 on 2018-07-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaximum', '0011_auto_20180715_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_amount',
            field=models.FloatField(blank=True, default=2, null=True, verbose_name='Минимальный остаток для отслеживания'),
        ),
        migrations.AddField(
            model_name='product',
            name='monitor_price',
            field=models.BooleanField(default=True, verbose_name='Отслеживать цену'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adress',
            field=models.CharField(blank=True, max_length=128, verbose_name='Адрес'),
        ),
    ]
