# Generated by Django 2.0.4 on 2018-07-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaximum', '0012_auto_20180715_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='monitor_amount',
            field=models.BooleanField(default=True, verbose_name='Отслеживать остаток'),
        ),
    ]
