# Generated by Django 2.0.4 on 2018-07-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaximum', '0014_price_value_recomend_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_value',
            name='monitor_price',
            field=models.BooleanField(default=True, verbose_name='Отслеживать цену'),
        ),
    ]
